### ISSUE TITLE
adding drug chart to identify concommitant and suspect

### ISSUE THREAD

**Issue by dbuijs** [hres/cvapps#10]

**Comment by dbuijs** [comment]
Need this on shinyfaers too

**Comment by aruu** [comment]
Not possible to do this with the openFDA API; only the reports themselves can be filtered, not drugs associated with reports.
For example:
https://api.fda.gov/drug/event.json?search=patient.drug.drugcharacterization:2&count=patient.drug.drugcharacterization

2 corresponds to concomitant, but it still contains drugs with value 1, meaning suspect. This is because it filters to **reports** containing any drug marked as concomitant, but when you count occurrences, it still includes all drugs associated with the reports -> suspect and concomitant are both included in the counts. Also thus, you can't get only reports with a specified drug marked as suspect.
