### ISSUE TITLE
Output Format

### ISSUE THREAD

**Issue by aruu** [hres/cvapps#135]
Output of the downloads in Excel: In French, the accents become symbols (such as @). This could be adjusted.

**Comment by bclaught** [comment]
Solution:
In Excel, do not just go to File->Open->*.csv file

This is because Excel reads any .csv as ANSI encoded, no matter if we encode it in UTF-8.

What you need to do to get the proper French characters is:

1. In Excel, go to the Data Tab.
2. Click on "From Text" under the "Get External Data" section.
3. Navigate to the directory where the file you saved is located.
4. An Import wizard will show up. In the drop down form, make sure you select Unicode UTF-8.
![image](https://cloud.githubusercontent.com/assets/13026068/22253806/e9d1ec9e-e220-11e6-8938-691e02a957d6.png)
5. After clicking next, make sure to select "Comma Delimited"
![image](https://cloud.githubusercontent.com/assets/13026068/22253895/26c8a8cc-e221-11e6-8133-d64cda6410ef.png)
6. Click next again and click finish.

The data should have properly loaded French characters now.
